apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-demo
  template:
    metadata:
      labels:
        app: harbor-demo
    spec:
      containers:
      - name: harbor-demo
        image: localhost/demo/harbor-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: harbor-demo-service
spec:
  type: NodePort
  selector:
    app: harbor-demo
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30007
